### ISSUE TITLE
how do you do shift+bsp=del?

### ISSUE THREAD

**Issue by sigul** [precondition/dactyl-manuform-keymap#1]
ehi man, couldn't find a way to contact you. your article on row mods is amazing! I'd like to implement shift+bsp to del but I wasn't able to find it in your code. could you point to it?

**Comment by precondition** [comment]
My implementation can be found [here](https://github.com/precondition/dactyl-manuform-keymap/blob/2e7614e4bff047143161ae943266d6415d48ff7f/keymap.c#L172-L197).

I've also opened a [pull request](https://github.com/qmk/qmk_firmware/pull/10550) on the upstream QMK repo to merge an explanation of the modifier detection as used in my Shift+Bksp to the QMK docs. You can read more about how it works in the "Files Changed" tab of the PR page.

**Comment by precondition** [comment]
If you're interested in overriding the behaviour of many Mod+Key combinations, take a look at this [new feature PR](https://github.com/qmk/qmk_firmware/pull/11422) by @JonasGessner (although I have yet to try it out myself).
