### ISSUE TITLE
ù

### ISSUE THREAD

**Issue by JonathanFerron** [precondition/dactyl-manuform-keymap#2]
J'aime la conception du keymap. Comment est-ce que tu tappes un ù avec ça? Manuellement avec AltGr + kc_grv, puis u?

**Comment by precondition** [comment]
Puisque ù est utilisée uniquement pour un seul mot en français, j'utilise une abbréviation dans [AutoKey](https://github.com/autokey/autokey) qui convertit « ouu » en « où » automatiquement. Dans les rares cas où il me faut la lettre « ù » séparément, j'utilise en effet <kbd>AltGr</kbd>+<kbd>`</kbd>, qui ont l'avantage d'être l'un à côté de l'autre (c'est par ailleurs mon utilisation principale du <kbd>AltGr</kbd>)

**Comment by JonathanFerron** [comment]
Fort bien pensé! J'utilise la dispo workman avec qq swaps (r <-> h et m <-> y), et ai mappé le ù comme un 'hold' sur la clef u, ce qui fonctionne bien aussi. Encore qq petites optimizations à faire et je soumettrai ensuite sur ta base de données.

Jonathan
________________________________
